/*
 * @author: Razvan Rauta
 * Date: 22.05.2019
 * Time: 11:11
*/

export const USER_LOGIN_SUCCESS ='USER_LOGIN_SUCCESS';
export const USER_SET_ID = 'USER_SET_ID';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const SONG_LIST_REQUEST = 'SONG_LIST_REQUEST';
export const SONG_LIST_RECEIVED = 'SONG_LIST_RECEIVED';
export const SONG_LIST_ERROR = 'SONG_LIST_ERROR';
export const SONG_LIST_ADD = 'SONG_LIST_ADD';
export const SONG_LIST_SET_PAGE ='SONG_LIST_SET_PAGE';

export const SONG_REQUEST = 'SONG_REQUEST';
export const SONG_RECEIVED = 'SONG_RECEIVED';
export const SONG_ERROR = 'SONG_ERROR';
export const SONG_UNLOAD = 'SONG_UNLOAD';
export const SONG_FORM_UNLOAD = 'SONG_FORM_UNLOAD';